name: Daily Auto Commit
on:
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12:00 UTC
  workflow_dispatch:       # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create timestamp file
        run: echo "Last update:$(date)" > timestamp.txt
        
      - name: Commit and push changes
        run: |
          git config --local user.email "21f1005042@ds.study.iitm.ac.in"
          git config --local user.name "GitHub Action"
          git add timestamp.txt
          git commit -m "Daily auto-commit: $(date)"
          git push
